<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>HeroesLobbyMessenger</AssemblyName>
    <RootNamespace>HeroesChatBot</RootNamespace>
    <Version>0.1.0</Version>
  </PropertyGroup>

</Project>